pipeline {
    agent any
    environment {
        GITLAB_CREDENTIAL = credentials('Anders_Github')
        CI = 'true'
    }

    stages {

        stage('pull git'){
            steps {
                git branch: 'main', credentialsId: 'Anders_Github', url: 'git@github.com:andeandr100/WSO2-deployment-single-node.git'
                sh ('ls -la')
           }
        }

        stage('build docker image'){
            steps {
                echo 'build docker image'
                sh ('whoami')
                sh ('pwd')
                sh ('cp mnt/storage/backup/wso2/client-truststore.jks client-truststore.jks')
                sh ('cp mnt/storage/backup/wso2/internal-keystore.jks internal-keystore.jks')
                sh ('cp mnt/storage/backup/wso2/tls-keystore.jks tls-keystore.jks')

                sh ('docker build -t wso2/am:latest .')
                sh ('docker tag wso2/am:latest localhost:32000/wso2:latest')
                sh ('docker push localhost:32000/wso2:latest')
           }
        }

        stage('deploy helm chart'){
            steps {

            }
        }
    }
}

